import React from "react";
import { Link } from "react-router-dom";
import { Text, Button, Img, Input } from "components";
import { CloseSVG } from "assets/images";

const Home = () => {
  const [framesixvalue, setFramesixvalue] = React.useState("");

  return (
    <React.Fragment>
      <div className="flex justify-between bg-white p-2 h-[12px]">
        <div className="flex flex-col gap-[5px] w-[4rem] lg:w-full">
          <Img
            className="h-[43px] md:h-auto object-cover"
            src="images/img_image3.png"
            alt="imageThree"
          />
          <Text
            className="text-[7.39px] text-teal-A400"
            size="txtPromptSemiBold739"
          >
            SENCHAT
          </Text>
        </div>

        <div className="mt-5">
          <Link
            to="/signup"
            className="text-teal-A400 text-center text-[22px] p-5 font-semibold"
          >
            Sign up
          </Link>

          <Link
            to="/signin"
            className="bg-teal-A400 cursor-pointer font-medium font-prompt p-4 rounded-[13px] text-black-900 text-lg"
          >
            Sign in
          </Link>
        </div>
      </div>

      <div className="px-5 h-[100vh] bg-gray-100 mt-20 flex sm:flex-col md:flex-row items-center justify-center gap-28 ">
        <div className="first-layout ">
          <h1 className="text-4xl front-prompt font-semibold">
            WELCOME TO SENCHAT
          </h1>
        </div>
        <div className="second-layout ">
          <Img
            className="w-60"
            src="images/img_rectangle2.png"
            alt="rectangle2"
          />
        </div>
      </div>

      {/* <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" faithful "}
         Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/desktopone">DesktopOne</Link>
        </li>
        <li>
        <Link to="/desktoptwo">DesktopTwo</Link>
        </li>
        <li>
          <Link to="/desktopthree">DesktopThree</Link>
        </li>
        <li>
          <Link to="/desktopfour">DesktopFour</Link>
        </li>
        <li>
          <Link to="/desktopfive">DesktopFive</Link>
        </li>
        <li>
          <Link to="/desktopsix">DesktopSix</Link>
        </li>
        <li>
          <Link to="/desktopseven">DesktopSeven</Link>
        </li>
        <li>
          <Link to="/desktopeight">DesktopEight</Link>
        </li>
        <li>
          <Link to="/desktopnine">DesktopNine</Link>
        </li>
        <li>
          <Link to="/desktopten">DesktopTen</Link>
        </li>
        <li>
          <Link to="/desktopeleven">DesktopEleven</Link>
        </li>
        <li>
          <Link to="/desktoptwelve">DesktopTwelve</Link>
        </li>
        <li>
        <Link to="/desktopthirteen">DesktopThirteen</Link>
        </li>
        <li>
          <Link to="/desktopfourteen">DesktopFourteen</Link>
        </li>
        <li>
          <Link to="/desktopfifteen">DesktopFifteen</Link>
        </li>
        <li>
          <Link to="/desktopsixteen">DesktopSixteen</Link>
        </li>
        <li>
          <Link to="/desktopseventeen">DesktopSeventeen</Link>
        </li>
        <li>
          <Link to="/desktopeighteen">DesktopEighteen</Link>
        </li>
        <li>
          <Link to="/desktopnineteen">DesktopNineteen</Link>
        </li>
        <li>
          <Link to="/desktoptwenty">DesktopTwenty</Link>
        </li>
      </ul> */}
    </React.Fragment>
  );
};
export default Home;
